### PR TITLE
Verification pass

### PR DESCRIPTION
**Pull request by emhane**
Defines `VerificationPass` and `VerificationCtx`

### CODE REVIEW

**Review by Y-Nak — CHANGES_REQUESTED** [review]
The overall design intent of this PR is unclear. Specifically, it's not clear how the actual passes will be managed, what granularity of parallelization is being considered, or how flexible you intend the verification pass system to be (e.g., will users be able to inject their own passes?).

Could you provide more details on your design approach so I can better understand your intentions?

**Comment by emhane** [comment]
> The overall design intent of this PR is unclear. Specifically, it's not clear how the actual passes will be managed, what granularity of parallelization is being considered, or how flexible you intend the verification pass system to be (e.g., will users be able to inject their own passes?).
> 

no parallelisation is being considered for starters, aiming to get the base in, and have a very simple verifier working first of all, then add complexity from there as next milestones.

can remove the `RwLock` around error stack in verification context for now, since parallelisation is out of scope.
> Could you provide more details on your design approach so I can better understand your intentions?

the verifier passes will be implemented on a function basis, not module basis, to start with. just like was done for graphviz, which is yet to be implemented on a module basis (should open issue for this).

**Comment by Y-Nak** [comment]
The main part that makes `VerificationCtx` complex more than necessary would be `PrimaryMap<PassRef, FuncRef>`.
I still think this is a misusage of `PrimaryMap`. If the pass needs to obtain the `Function` definition, it's enough that the pass takes `FuncRef` and asks it by calling `VerificationCtx::func_data`.
Why do you need to define `PassRef`? I don't see any advantage to using it from the current implementation/design.

**Comment by emhane** [comment]
> The main part that makes `VerificationCtx` complex more than necessary would be `PrimaryMap<PassRef, FuncRef>`. I still think this is a misusage of `PrimaryMap`. If the pass needs to obtain the `Function` definition, it's enough that the pass takes `FuncRef` and asks it by calling `VerificationCtx::func_data`. Why do you need to define `PassRef`? I don't see any advantage to using it from the current implementation/design.

agreed, I have shrunk the scope to better fit the function-basis passes that I will implement to start with
https://github.com/fe-lang/sonatina/blob/5e919c74347f23b1e666570f3b71ace0a5f7522e/crates/verifier/src/error/kind.rs#L11-L34

**Comment by emhane** [comment]
blocked by https://github.com/fe-lang/sonatina/pull/69

**Comment by Y-Nak** [comment]
@emhane Would you rebase to the master? Sorry for the inconvenience.

**Comment by emhane** [comment]
> @emhane Would you rebase to the master? Sorry for the inconvenience.

done @Y-Nak

**Review by Y-Nak — APPROVED** [review]
LGTM

**Pull request merged**
