### PR TITLE
[Enh]: Improving the error messages for module_linker

### LINKED ISSUE #98: Enhance Error Messages in `ModuleLinker`
In #96, `ModuleLiker` is introduced. However, the error messages generated by `ModuleLinker` need to be improved for better clarity and usability. The current messages are often vague and make debugging difficult.

To improve the debugging experience, error messages generated by `ModuleLinker` for inconsistent declarations should provide more detailed information. Specifically:
1. **Identify the Modules Involved**: Clearly indicate which modules have conflicting declarations.
2. **Describe the Inconsistency**: Clearly explain the exact reason for the inconsistency (e.g., the linkage or the type definition is inconsistent).

### PR DESCRIPTION
**Pull request by nakul-py**
- This PR Improves the Module Linker error messages.
 closes #98

### CODE REVIEW

**Comment by Y-Nak** [comment]
Thank you for your contribution to the project!

However, upon reviewing this pull request, it seems that the changes proposed are unrelated to the scope of the original issue. The issue specifically refers to enhancing error messages generated by the `ModuleLinker` component. The modifications in this PR appear to focus on test-related error formatting, which is not directly connected to the `ModuleLinker`.

If you’d like to contribute to the original issue, please consider reviewing the `ModuleLinker` implementation. If you have any questions, feel free to ask me!

**Comment by nakul-py** [comment]
Will i contribute to this branch [Y-Nak:ir-module-linking](https://github.com/Y-Nak/sonatina/tree/ir-module-linking)

**Comment by Y-Nak** [comment]
Yes, it's the correct branch. Please refer to `crates/codegen/src/module_linker.rs`. Curretly, it's not possible to specify the module name, so please start from `2.  Describe the Inconsistency`, or just add the `name: String` field to `Module` and tweak `ModuleBuider`. Thank you.

**Comment by nakul-py** [comment]
I can't able to work  in  https://github.com/Y-Nak/sonatina/tree/ir-module-linking  as i have forked the main repository https://github.com/fe-lang/sonatina. Will you merge your module-linking pr https://github.com/fe-lang/sonatina/pull/96 to the main repo.

**Comment by Y-Nak** [comment]
#96 is merged. I moved the `module_linker.rs` to `crates/ir/src/module_linker.rs`. Please refer to it.

**Comment by Y-Nak** [comment]
Close this PR in favor of #102

**Pull request closed without merging**
